name: Code Coverage

on:
  workflow_call:
    secrets:
      codecov_token:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  Template:
    runs-on: ubuntu-latest
    
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    
    steps:
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run `cargo-tarpaulin`
        run: |
          cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out xml --fail-under 50 --exclude-files src/external/**/* src/external/*

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.codecov_token }}

      - name: Archive Results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml
