name: Code Coverage

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    
    steps:
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run `cargo-tarpaulin`
        run: |
          cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out xml --fail-under 50

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Archive Results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml
